Mvc/Controllers/AsyncConcurrentController.cs
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Mvc.Controllers
{
    public class AsyncConcurrentController : Controller
    {
        // GET: /Index/
        public async Task<ActionResult> Index()
        {
            var startTime = DateTime.Now;

            var doSomething = DoSomethingAsync();
            Thread.Sleep(1000);
            await doSomething;
            
            var timeTaken = DateTime.Now.Subtract(startTime);
            var output = timeTaken.TotalSeconds + " seconds";

            return RedirectToAction("Index", "Home", new { Output = output });
        }

        private async Task DoSomethingAsync()
        {
            await Task.Delay(1)
                // *** difference ***
                      .ConfigureAwait(continueOnCapturedContext: false);
            //Lets go of context here
            
            Thread.Sleep(1000);
        }


     }
}

Mvc/Controllers/AsyncNotConcurrentController.cs
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Mvc.Controllers
{
    public class AsyncNotConcurrentController : Controller
    {
        // GET: /Index/
        public async Task<ActionResult> Index()
        {
            var startTime = DateTime.Now;

            var doSomething = DoSomethingAsync();
            Thread.Sleep(1000);
            await doSomething;
            
            var timeTaken = DateTime.Now.Subtract(startTime);
            var output = timeTaken.TotalSeconds + " seconds";

            return RedirectToAction("Index", "Home", new { Output = output });
        }

        private async Task DoSomethingAsync()
        {
            await Task.Delay(1);
            Thread.Sleep(1000);
        }


     }
}

Mvc/Controllers/FailEarlyFailLoudlyController.cs
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Mvc.Controllers
{
    public class FailEarlyFailLoudlyController : Controller
    {
        // GET: /Index/
        public async Task<ActionResult> Index()
        {
            await DoSomethingAsync()
                      .ConfigureAwait(continueOnCapturedContext: false);

            var output = "Success. Http verb used: " +
                         System.Web.HttpContext.Current.Request.HttpMethod;

            return RedirectToAction("Index", "Home", new { Output = output });
        }

        private async Task DoSomethingAsync()
        {
            await Task.Delay(1000)
                      .ConfigureAwait(continueOnCapturedContext: false);
        }


     }
}

Mvc/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Mvc.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        public ActionResult Index(string output)
        {
            ViewBag.Output = output;
            return View();
        }


     }
}

Mvc/Controllers/UseGatekeeperController.cs
using System;
using System.Web.Mvc;
using Mvc.Extras.Gatekeeper;

namespace Mvc.Controllers
{
    public class UseGatekeeperController : Controller
    {
        private readonly IGatekeeperExample _gatekeeperExample;

        public UseGatekeeperController(IGatekeeperExample gatekeeperExample)
        {
            _gatekeeperExample = gatekeeperExample;
        }

        // GET: /Index/
        public ActionResult Index(int dividend, int divisor)
        {
            var result = GetResult(dividend, divisor);

            return RedirectToAction("Index", "Home", new { Output = result });
        }


        private string GetResult(int dividend, int divisor)
        {
            try
            {
                #pragma warning disable 618
                //justification: I have a really, really good reason not to implement
                //async all the way up right now
                var quotient = _gatekeeperExample.DivideSlowly(dividend, divisor);
                #pragma warning restore 618
                return "Success. Quotient = " + quotient;
            }
            catch (DivideByZeroException)
            {
                return "Failure. Division by zero.";
            }
        }


     }
}

Mvc/Views/Home/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "TPL and async/await code samples";
}

<p>Output: @(ViewBag.Output ?? "n/a")</p>

<p>@Html.ActionLink("Deadlock", "Index", "Deadlock")</p>
<p>@Html.ActionLink("Deadlock fixed using .ConfigureAwait(continueOnCapturedContext: false)", "Index", "DeadLockFixedNoCapture")</p>
<p>@Html.ActionLink("Deadlock fixed using ThreadPool technique", "Index", "DeadLockFixedThreadPool")</p>
<p>@Html.ActionLink("Aynsc not so concurrent", "Index", "AsyncNotConcurrent")</p>
<p>@Html.ActionLink("Aynsc concurrent", "Index", "AsyncConcurrent")</p>
<p>@Html.ActionLink("Fail early, fail loudly", "Index", "FailEarlyFailLoudly")</p>
<p>@Html.ActionLink("Successful context access", "Index", "SuccessfulContextAccess")</p>
<p>@Html.ActionLink("Use Gatekeeper Example - 10 ÷ 5", "Index", "UseGatekeeper", new { dividend = 10, divisor = 5 }, null)</p>
<p>@Html.ActionLink("Use Gatekeeper Example - 10 ÷ 0", "Index", "UseGatekeeper", new { dividend = 10, divisor = 0 }, null)</p>

Mvc/Views/Home/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>